### ISSUE TITLE
C Headers

### ISSUE THREAD

**Issue by alanswx** [snipsco/tensorflow-build#9]
Thank you for these great scripts.  Have you thought about adding the necessary C headers into the installer packages so that it would be trivial to build C code on a pi, etc?

**Comment by fredszaq** [comment]
Yes we should add them to the debian packages (they're already present in the Archlinux & macOS packages) I'll add that tonight

**Comment by kali** [comment]
LGTM.

**Comment by fredszaq** [comment]
PR merged, links to the newly built debs in the readme
